name = "Hopcraft"
author = "RawrbearHS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cd9673e911fb82c79645bb4bdf071b2a718836a9490ce65aef99c4c65bea461"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
