name = "Hopcraft"
author = "RawrbearHS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5bbadaa3de904b0159932e72a2c88bc94772d79dc1f10843787f1290423a492"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
