name = "Hopcraft"
author = "Treeways"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89eb94d2a78afec7aaf9c6b836707224488c24d834e55eaa0d9a2ccb42108d15"

[versions]
fabric = "0.16.11"
minecraft = "1.21.5"
