name = "Hopcraft"
author = "Treeways"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b7c7d0bac05de8737eea1cba61dff64446d3e11d77c1fc456290a1ac7817e0"

[versions]
fabric = "0.16.11"
minecraft = "1.21.5"
