name = "HopcraftNeoForge"
author = "RawrbearHS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef420b9f65d609f0f31f6ef147efe3b17e782af6854235e2069eeea51fedda37"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.143"
