name = "Hopcraft"
author = "RawrbearHS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8939b56abd4a6ce0528b5901fb0c6b725a3c99596a336a33de98f4a74b67f52c"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
