name = "Hopcraft"
author = "RawrbearHS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce224fc4879f97ce68aebd43cc804e87c5cbe4689e6f3ff4df341af55fe6925"

[versions]
fabric = "0.16.13"
minecraft = "1.21.1"
